language: ruby
rvm:
  - 2.0.0
gemfile: Gemfile
after_install: gem list
script: bundle exec rake build
notifications:
  email:
    #recipients:
    #  - dev@lists.openshift.redhat.com
  irc:
    - "irc.freenode.org#openshift-dev"
